mopad_admin:
    resource: "@MoPadAdminBundle/Resources/config/routing.yml"
    prefix:   /mopad

acme_store:
    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
    prefix:   /store

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

# AdminBundle http://mopad-symfony.de/web/app_dev.php/admin/dashboard
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin