<?php
/**
 * (C) MoPad
 */
namespace MoPad\AdminBundle\Entity;

use Sonata\UserBundle\Entity\BaseGroup as BaseGroup;

/**
 * The Group entity represent a authentication role.
 *
 * This file has been generated by the Sonata EasyExtends bundle {@link http://sonata-project.org/easy-extends }
 *
 * References :
 *   working with object : {@Link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en}
 * 
 * @package MoPad\AdminBundle\Entity
 */
class Group extends BaseGroup
{

    /**
	 * id
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
}