acme_store_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeStoreBundle:Default:index, name: defaultname }

_acme_store_create:
    pattern:  /create
    defaults: { _controller: AcmeStoreBundle:Default:create }
    
_acme_store_show:
    pattern: /show/{id}
    defaults: { _controller: AcmeStoreBundle:Default:show }

_acme_store_update:
    pattern: /update/{id}
    defaults: { _controller: AcmeStoreBundle:Default:update }

_acme_store_remove:
    pattern: /remove/{id}
    defaults: { _controller: AcmeStoreBundle:Default:remove }

_acme_store_search:
    pattern: /search
    defaults: { _controller: AcmeStoreBundle:Default:search }

_acme_store_search2:
    pattern: /search2
    defaults: { _controller: AcmeStoreBundle:Default:search2 }